---
title: "wine"
author: "Curtis Easton"
date: "2024-11-20"
output: html_document
---

```{r setup}

options(repos = c(CRAN = "https://cloud.r-project.org"))

```

## load data

```{r}

# Load Necessary Libraries
library(dplyr) # For data manipulation

# Load the Red Wine Data
red_wine = read.csv("winequality-red.csv", sep = ";")

# Load the White Wine Data
white_wine = read.csv("winequality-white.csv", sep = ";")

# Add a Categorical Variable for Wine Type
red_wine$type = "Red"
white_wine$type = "White"

# Combine the Two Datasets
wine_data = bind_rows(red_wine, white_wine)


# Convert 'type' to a Factor
wine_data$type = as.factor(wine_data$type)

nrow(wine_data)


# remove outliers
res_sugar_6580 = which(wine_data$residual.sugar == 65.80)
free_sulf_dio_289 = which(wine_data$free.sulfur.dioxide == 289.0)
dens_10103 = which(wine_data$density == 1.0103)

remove_idx = c(res_sugar_6580, free_sulf_dio_289, dens_10103)
wine_data = wine_data[-remove_idx, ]
nrow(wine_data)

# View(wine_data)

```

<!-- ```{r} -->
<!-- train_idx = sample(nrow(wine_data), 5194) -->
<!-- wine_data_train = wine_data[train_idx, ] -->
<!-- wine_data_test = wine_data[-train_idx, ] -->
<!-- ``` -->




<!-- ```{r} -->
<!-- wine_1 = wine_data[wine_data$quality == 9, ] -->
<!-- nrow(wine_1) -->
<!-- ``` -->




<!-- ## Data types -->


<!-- ```{r} -->

<!-- str(wine_data) -->

<!-- ``` -->



<!-- ## Fit additive Model -->

<!-- ```{r} -->

<!-- model = lm(quality ~ ., data = wine_data) -->
<!-- summary(model) -->

<!-- ``` -->




<!-- ```{r} -->
<!-- set.seed(1234) -->
<!-- subset_idx = sample(nrow(wine_data), 70) -->
<!-- wine_data_subset = wine_data[subset_idx, ] -->

<!-- wine_data_subset$quality = jitter(wine_data_subset$quality, factor = 2.0) -->

<!-- pairs(wine_data_subset, col = "dodgerblue") -->
<!-- ``` -->





```{r}
get_loocv_rmse = function(model) {
  sqrt(mean((resid(model) / (1 - hatvalues(model))) ^ 2))
}

get_adj_r2 = function(model) {
  summary(model)$adj.r.squared
}
```



<!-- ```{r} -->
<!-- log_quality_model = lm(log(quality) ~ .^2, data = wine_data_train) -->
<!-- log_quality_back_aic = step( -->
<!--   log_quality_model, -->
<!--   direction = "backward", -->
<!--   trace = 0 -->
<!-- ) -->

<!-- get_loocv_rmse(log_quality_back_aic) -->
<!-- get_adj_r2(log_quality_back_aic) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library(leaps) -->
<!-- log_quality_exh = summary(regsubsets(log(quality) ~ ., data = wine_data_train, really.big=TRUE)) -->

<!-- log_quality_exh$which -->
<!-- ``` -->

<!-- ```{r} -->
<!-- red_wine_model = lm(log(quality) ~ volatile.acidity + sulphates + alcohol, data = wine_data_train) -->

<!-- get_loocv_rmse(red_wine_model) -->
<!-- get_adj_r2(red_wine_model) -->
<!-- ``` -->



<!-- # ```{r} -->
<!-- # big_model = lm(log(quality) ~ . + type:fixed.acidity + type:volatile.acidity + type:citric.acid + type:residual.sugar + type:chlorides + type:density + type:free.sulfur.dioxide + type:total.sulfur.dioxide + type:pH + type:sulphates + type:alcohol, data = wine_data_train) -->
<!-- #  -->
<!-- # n = length(resid(big_model)) -->
<!-- #  -->
<!-- # model_back_bic = step( -->
<!-- #   big_model, -->
<!-- #   direction = "backward", -->
<!-- #   k = log(n), -->
<!-- #   trace = 0 -->
<!-- # ) -->
<!-- #  -->
<!-- # summary(model_back_bic) -->
<!-- #  -->
<!-- # get_loocv_rmse(model_back_bic) -->
<!-- # get_adj_r2(model_back_bic) -->
<!-- # ``` -->


<!-- # ```{r} -->
<!-- # red_wine_data_train = wine_data_train[wine_data_train$type == "Red", ] -->
<!-- # red_wine_data_test = wine_data_test[wine_data_test$type == "Red", ] -->
<!-- # ``` -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # ```{r} -->
<!-- # m = lm(quality ~ volatile.acidity + alcohol, data = red_wine_data_train) -->
<!-- #  -->
<!-- # get_loocv_rmse(m) -->
<!-- # get_adj_r2(m) -->
<!-- ``` -->














```{r}
min_max_scale = function(col) {
  x = col
  x_min = min(col)
  x_max = max(col)
  
  (x - x_min) / (x_max - x_min)
}
```

```{r}
# wine_data$quality = wine_data$quality + rnorm(nrow(wine_data), mean = 0, sd = 1.0)


for(i in 1:ncol(wine_data)){
  if(i == 13 | i == 12) next
  wine_data[, i] = min_max_scale(wine_data[, i])
}

# wine_data[, 12] = min_max_scale(wine_data[, 12])

# wine_data[, 12] = (wine_data[, 12] - 0) / (10 - 0)
```



<!-- ```{r} -->
<!-- subset_idx = sample(nrow(wine_data), 500) -->
<!-- wine_data_subset = wine_data[subset_idx, ] -->
<!-- # wine_data_subset$quality = jitter(wine_data_subset$quality, factor = 1.0) -->
<!-- # plot(quality ~ ., data = wine_data_subset) -->
<!-- # pairs(wine_data_subset) -->
<!-- # plot(quality ~ ., data = wine_data_subset) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- wine_data$quality = wine_data$quality + 0.5 -->
<!-- wine_data$quality = log(wine_data$quality) -->

<!-- set.seed(1234) -->
<!-- subset_idx = sample(nrow(wine_data), 70) -->
<!-- wine_data_subset = wine_data[subset_idx, ] -->

<!-- wine_data_subset$quality = jitter(wine_data_subset$quality, factor = 1.0) -->

<!-- pairs(wine_data_subset, col = "dodgerblue") -->
<!-- ``` -->


```{r}
# wine_data$quality = log(wine_data$quality / (1 - wine_data$quality))
```





```{r}
train_idx = sample(nrow(wine_data), 5194)
wine_data_train = wine_data[train_idx, ]
wine_data_test = wine_data[-train_idx, ]
```


```{r}
library(faraway)
library(MASS)
library(lmtest)
```


```{r}
# + type:.
add_model = lm(quality ~ . + type:. - pH - type:pH, data = wine_data_train)
n = length(resid(add_model))

back_bic = step(
  add_model,
  direction = "backward",
  k = log(n),
  trace = 0
)

get_loocv_rmse(back_bic)
get_adj_r2(back_bic)
vif(back_bic)

summary(back_bic)




boxcox(back_bic, plotit = TRUE, lambda = seq(0.5, 1.2, 0.05))
```

```{r}
int_model = lm(quality ~ volatile.acidity
               + chlorides + free.sulfur.dioxide
               + density + sulphates
               + alcohol + volatile.acidity:type,
               data = wine_data)

get_loocv_rmse(int_model)
get_adj_r2(int_model)
vif(int_model)

summary(int_model)



plot(fitted(int_model), resid(int_model))
abline(h = 0)

bptest(int_model)

qqnorm(resid(int_model))
qqline(resid(int_model), col = "dodgerblue")



boxcox(int_model, plotit = TRUE, lambda = seq(0.5, 1.2, 0.05))
```


```{r}
int_model_boxcox = lm((((quality ^ 0.7) - 1) / 0.7) ~ volatile.acidity
               + chlorides + free.sulfur.dioxide
               + sulphates
               + alcohol + volatile.acidity:type,
               data = wine_data_train)

get_loocv_rmse(int_model_boxcox)
get_adj_r2(int_model_boxcox)
vif(int_model_boxcox)

summary(int_model_boxcox)
```


```{r}
plot(fitted(int_model_boxcox), resid(int_model_boxcox))
abline(h = 0)
```

```{r}
bptest(int_model_boxcox)
```

```{r}
qqnorm(resid(int_model_boxcox))
qqline(resid(int_model_boxcox), col = "dodgerblue")
```



<!-- ## VIF Values -->


<!-- ```{r} -->
<!-- if (!require(car)) install.packages("car") -->
<!-- library(car) -->

<!-- # Compute VIF Values -->
<!-- vif_values = vif(model) -->

<!-- # Display the VIF Values -->
<!-- vif_values -->


<!-- ``` -->

<!-- ## Fit interaction model -->

<!-- ```{r} -->


<!-- model = lm(quality ~ .^2, data = wine_data) -->
<!-- summary(model) -->


<!-- ``` -->

<!-- ## Including Plots -->


<!-- ```{r} -->

<!-- # Histogram of Quality with Normal Distribution Overlay -->
<!-- hist(wine_data$quality, -->
<!--      breaks = 10,  # Adjust number of bins -->
<!--      probability = TRUE,  # Scale histogram to show probabilities -->
<!--      main = "Histogram of Wine Quality with Normal Distribution", -->
<!--      xlab = "Wine Quality", -->
<!--      col = "lightblue", -->
<!--      border = "black") -->

<!-- # Calculate scaling factor for the normal curve -->
<!-- scale_factor = 0.8 / max(dnorm(x = seq(min(wine_data$quality), max(wine_data$quality), length = 100), -->
<!--                                mean = mean(wine_data$quality), -->
<!--                                sd = sd(wine_data$quality))) -->

<!-- # Overlay scaled normal distribution curve -->
<!-- curve(dnorm(x, mean = mean(wine_data$quality), sd = sd(wine_data$quality)) * scale_factor, -->
<!--       col = "red", -->
<!--       lwd = 2, -->
<!--       add = TRUE) -->



<!-- # Scatter plot: Volatile Acidity vs Quality -->
<!-- plot(wine_data$volatile.acidity, wine_data$quality, -->
<!--      main = "Volatile Acidity vs Wine Quality", -->
<!--      xlab = "Volatile Acidity", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "blue", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Residual Sugar vs Quality -->
<!-- plot(wine_data$residual.sugar, wine_data$quality, -->
<!--      main = "Residual Sugar vs Wine Quality", -->
<!--      xlab = "Residual Sugar", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "green", pch = 19, cex = 0.5) -->


<!-- # Scatter plot: Fixed Acidity vs Quality -->
<!-- plot(wine_data$fixed.acidity, wine_data$quality, -->
<!--      main = "Fixed Acidity vs Wine Quality", -->
<!--      xlab = "Fixed Acidity", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "purple", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Citric Acid vs Quality -->
<!-- plot(wine_data$citric.acid, wine_data$quality, -->
<!--      main = "Citric Acid vs Wine Quality", -->
<!--      xlab = "Citric Acid", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "orange", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Chlorides vs Quality -->
<!-- plot(wine_data$chlorides, wine_data$quality, -->
<!--      main = "Chlorides vs Wine Quality", -->
<!--      xlab = "Chlorides", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "red", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Free Sulfur Dioxide vs Quality -->
<!-- plot(wine_data$free.sulfur.dioxide, wine_data$quality, -->
<!--      main = "Free Sulfur Dioxide vs Wine Quality", -->
<!--      xlab = "Free Sulfur Dioxide", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "cyan", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Total Sulfur Dioxide vs Quality -->
<!-- plot(wine_data$total.sulfur.dioxide, wine_data$quality, -->
<!--      main = "Total Sulfur Dioxide vs Wine Quality", -->
<!--      xlab = "Total Sulfur Dioxide", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "brown", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Density vs Quality -->
<!-- plot(wine_data$density, wine_data$quality, -->
<!--      main = "Density vs Wine Quality", -->
<!--      xlab = "Density", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "pink", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: pH vs Quality -->
<!-- plot(wine_data$pH, wine_data$quality, -->
<!--      main = "pH vs Wine Quality", -->
<!--      xlab = "pH", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "darkgreen", pch = 19, cex = 0.5) -->

<!-- # Scatter plot: Sulphates vs Quality -->
<!-- plot(wine_data$sulphates, wine_data$quality, -->
<!--      main = "Sulphates vs Wine Quality", -->
<!--      xlab = "Sulphates", -->
<!--      ylab = "Wine Quality", -->
<!--      col = "darkblue", pch = 19, cex = 0.5) -->

<!-- ``` -->


